coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 50%
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
